<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>14</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
      <Reference Include="Assembly-CSharp" Publicize="true" />
      <Reference Include="Assembly-CSharp-firstpass" />
      <Reference Include="CommandSystem.Core" />
      <Reference Include="Mirror" />
      <Reference Include="Pooling" />
      <Reference Include="UnityEngine.CoreModule" />
      <Reference Include="UnityEngine.PhysicsModule" />
    </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="Northwood.LabAPI" Version="1.1.7" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" PrivateAssets="all" />
  </ItemGroup>

</Project>
